name: Build App
on:
  push:
    branches-ignore:
      - build
  workflow_dispatch:
  pull_request:
jobs:
  buildLnx:
    name: Debian/RedHat Package(.deb, .rpm)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: false 
      - name: Install Dependencies
        run: npm i
      - name: Install rpm, fakeroot, and dpkg
        run: sudo apt install rpm fakeroot dpkg
      - name: Build
        run: npm run make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: lnx
          path: out/make
  buildMac:
    name: macOS Application(.dmg)
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: false 
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: mac
          path: out/make
  buildWin:
    name: Windows Executable(.exe)
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: false 
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: win
          path: out/make
  deploy:
    needs: [buildLnx, buildMac, buildWin]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: lnx
      - name: Deploy Linux Packages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: build
          FOLDER: lnx/out/make
      - name: Deploy macOS Application
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: build
          FOLDER: mac/out/make
      - name: Deploy Windows Executable
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: build
          FOLDER: win/out/make